// Turns the official Mojang JSON Schemas into the .d.ts files the IDE reads.
//
// Two sources have to be stitched together, because neither is complete on its
// own: the `schemas/` tree carries the document roots and the block/entity
// component containers, while the item component list only exists in the
// hand-authored `types/` tree that ships alongside it. Items therefore get
// their `components` grafted in via json-schema-to-typescript's `tsType`
// escape hatch, pointing at the vendored declaration.

const fs = require("fs");
const path = require("path");

/** Copied out of the schema package so item components resolve. Keeping the
 *  original layout means the `../../../common` imports inside them still work. */
const VENDOR_FILES = [
  "common/index.d.ts",
  "bp/items/components/MinecraftItemV1260.d.ts",
  "bp/items/components/MinecraftItemV12190.d.ts",
];

const ITEM_COMPONENTS_UNION = [
  "MinecraftItemV1260Components",
  "MinecraftItemV12190Components",
];

/**
 * Bumped whenever this file changes the shape of what it emits. It keys both the
 * normalized-schema-tree marker and the caller's `.generated` marker, so an
 * existing cache and an existing types folder both rebuild on upgrade.
 */
const TYPES_REVISION = 2;

const HEADER = [
  "// AUTOGENERATED by @bedrock-core/generator — do not edit.",
  "// Source: @minecraft/bedrock-schemas (MIT, © Microsoft Corporation).",
  "",
].join("\n");

/**
 * Names TypeScript's own libs already put in global scope. Redeclaring one is a
 * duplicate-identifier error, and `Animation` really does collide with the DOM
 * lib, which is on by default unless a project narrows `lib`.
 */
const RESERVED_GLOBALS = new Set([
  "Animation", "Attr", "Audio", "Blob", "Cache", "Comment", "Console", "Crypto",
  "Document", "Element", "Event", "File", "Headers", "History", "Image",
  "Location", "Lock", "Navigator", "Node", "Notification", "Option",
  "Performance", "Plugin", "Range", "Report", "Request", "Response", "Screen",
  "Selection", "Sensor", "Storage", "Text", "Touch", "Window", "Worker",
]);

/**
 * Short global alias for a category — `bp/blocks` becomes `Block`. These are
 * what make plain `export default { … } satisfies Block` work without an
 * import, so templates never have to call a helper function.
 *
 * One rule handles both kinds of clash: if the plain name is taken — by another
 * category, or by a standard-lib global — fall back to prefixing the pack, so
 * `rp/entity` becomes `RpEntity` and `bp/animations` becomes `BpAnimation`.
 */
function categoryAlias(key, taken, prefix = "") {
  const [pack] = key.split("/");
  const last = key.split("/").pop();
  const base = pascalCase(last.replace(/ies$/, "y").replace(/s$/, ""));

  let name = `${prefix}${base}`;
  if (taken.has(name) || RESERVED_GLOBALS.has(name)) name = `${prefix}${pascalCase(pack)}${base}`;
  while (taken.has(name) || RESERVED_GLOBALS.has(name)) name += "_";

  taken.add(name);
  return name;
}

/** `./schemas/bp/blocks/index.schema.json` -> `bp/blocks`
 *  `./schemas/bp/functions/tick.schema.json` -> `bp/functions/tick` */
function categoryKey(url) {
  return url
    .replace(/^\.?\//, "")
    .replace(/^schemas\//, "")
    .replace(/\/index\.schema\.json$/, "")
    .replace(/\.schema\.json$/, "");
}

function pascalCase(text) {
  const name = text
    .replace(/[^A-Za-z0-9]+/g, " ")
    .trim()
    .split(" ")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");
  return /^[A-Za-z]/.test(name) ? name : `Schema${name}`;
}

/**
 * json-schema-to-typescript names types after `title`, and a few upstream
 * schemas carry titles that are not usable identifiers — `languages.json`
 * titles its entries "1", "2", "3", which compiles to `export type 1 = string`.
 * Dropping those titles lets the generator fall back to its own auto-naming.
 */
function sanitizeTitles(node) {
  if (Array.isArray(node)) {
    node.forEach(sanitizeTitles);
    return;
  }
  if (!node || typeof node !== "object") return;

  if (typeof node.title === "string" && !/^[A-Za-z_$]/.test(node.title.replace(/[^A-Za-z0-9_$]/g, ""))) {
    delete node.title;
  }

  for (const value of Object.values(node)) sanitizeTitles(value);
}

/** Types json-schema-to-typescript can write inline without losing anything. */
const SCALAR_TYPES = new Set(["string", "number", "integer", "boolean"]);

/**
 * json-schema-to-typescript hoists every subschema that carries a `title` into
 * its own named type, so a plain `{ "title": "Value", "type": "number" }`
 * property compiles to `export type Value15 = number` with the interface
 * reading `value?: Value15` — a deduplicated name that says nothing, and the
 * property's own description parked on the alias rather than on the property.
 * There are 2500-odd of those across the package.
 *
 * Dropping the title inlines the type and moves the doc comment onto the
 * property, which is where the IDE shows it on hover. Titles on `enum`/`const`
 * nodes stay: those name real unions (`SurfaceBuilderType`, …) worth referring
 * to, and inlining them would repeat the whole union at every use site.
 */
function inlineScalarTitles(node) {
  if (Array.isArray(node)) {
    node.forEach(inlineScalarTitles);
    return;
  }
  if (!node || typeof node !== "object") return;

  for (const value of Object.values(node)) inlineScalarTitles(value);

  if (typeof node.title !== "string") return;
  if (!SCALAR_TYPES.has(node.type)) return;
  if (node.enum !== undefined || node.const !== undefined) return;

  delete node.title;
}

/** Keys that mean a node actually describes a shape. */
const SHAPE_KEYS = [
  "properties",
  "patternProperties",
  "additionalProperties",
  "required",
  "allOf",
  "anyOf",
  "oneOf",
  "not",
  "$ref",
  "enum",
  "const",
  "items",
];

/** Keywords that only mean anything for strings or arrays. An `object` node
 *  carrying one of these contradicts itself, which upstream does when a scalar
 *  got mis-encoded — `minecraft:map_color` is the string "#9acd32" but is
 *  published as an object with minLength/maxLength. */
const SCALAR_ONLY_KEYS = ["minLength", "maxLength", "pattern", "format", "minItems", "maxItems"];

/**
 * Several components are declared as a bare `{"type": "object"}` in the
 * aggregate component lists — `minecraft:friction` is really a number, but the
 * schema says object with no properties. Compiling that to
 * `{ [k: string]: unknown }` turns valid templates into type errors, so a node
 * that carries no shape information — or that contradicts its own declared type
 * — becomes `unknown` instead: permissive, and honest about the fact that the
 * schema does not actually describe it.
 */
function relaxShapelessObjects(node) {
  if (Array.isArray(node)) {
    node.forEach(relaxShapelessObjects);
    return;
  }
  if (!node || typeof node !== "object") return;

  for (const value of Object.values(node)) relaxShapelessObjects(value);

  if (node.type !== "object" || node.tsType) return;

  const shapeless = !SHAPE_KEYS.some((k) => node[k] !== undefined);
  const contradictory = SCALAR_ONLY_KEYS.some((k) => node[k] !== undefined);

  if (shapeless || contradictory) node.tsType = "unknown";
}

/** Cheap syntactic sanity check, so one malformed category cannot take the
 *  whole project's typecheck down with it. */
function looksLikeValidTs(body) {
  return !/\bexport\s+(?:type|interface)\s*(?:=|\d|$)/m.test(body);
}

/**
 * The fix-ups have to reach every schema file, not just the 39 entry points —
 * `minecraft:friction` is defined in a `$ref`'d component list that
 * json-schema-to-typescript reads straight off disk. So the unpacked tree is
 * normalized in place, once per schema-package version.
 */
function normalizeSchemaTree(schemasRoot, log) {
  const marker = path.join(schemasRoot, `.normalized-v${TYPES_REVISION}`);
  if (fs.existsSync(marker)) return;

  let count = 0;
  const walk = (dir) => {
    for (const item of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, item.name);
      if (item.isDirectory()) {
        walk(full);
      } else if (item.name.endsWith(".json")) {
        const schema = JSON.parse(fs.readFileSync(full, "utf8"));
        sanitizeTitles(schema);
        inlineScalarTitles(schema);
        relaxShapelessObjects(schema);
        fs.writeFileSync(full, JSON.stringify(schema), "utf8");
        count++;
      }
    }
  };

  walk(schemasRoot);
  fs.writeFileSync(marker, "", "utf8");
  log(`✅ normalized ${count} schema files`);
}

function copyVendorFiles(typesRoot, vendorDir, log) {
  let copied = 0;
  for (const rel of VENDOR_FILES) {
    const src = path.join(typesRoot, rel);
    if (!fs.existsSync(src)) {
      log(`⚠️  vendor file missing from schema package, skipping: ${rel}`);
      continue;
    }
    const dest = path.join(vendorDir, rel);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(src, dest);
    copied++;
  }
  return copied;
}

/**
 * Compile every category in the schema package's catalog into `outDir`.
 *
 * @param {{ pkgRoot: string, outDir: string, strict: boolean, typePrefix?: string, log(msg: string): void }} opts
 * @returns {Promise<Array<{ key: string, rootName: string, module: string, fileMatch: string[] }>>}
 */
async function compileCatalog({ pkgRoot, outDir, strict, typePrefix = "", log }) {
  const { compileFromFile } = require("json-schema-to-typescript");

  const catalog = JSON.parse(fs.readFileSync(path.join(pkgRoot, "catalog.json"), "utf8"));

  normalizeSchemaTree(path.join(pkgRoot, "schemas"), log);
  const vendorCopied = copyVendorFiles(path.join(pkgRoot, "types"), path.join(outDir, "vendor"), log);

  const categories = [];
  const usedNames = new Set();
  const usedAliases = new Set();

  for (const entry of catalog.schemas) {
    const key = categoryKey(entry.url);
    const schemaFile = path.join(pkgRoot, entry.url.replace(/^\.?\//, ""));

    if (!fs.existsSync(schemaFile)) {
      log(`⚠️  catalog points at a missing schema, skipping: ${entry.url}`);
      continue;
    }

    const schema = JSON.parse(fs.readFileSync(schemaFile, "utf8"));
    sanitizeTitles(schema);
    inlineScalarTitles(schema);
    relaxShapelessObjects(schema);

    // Items: swap the schema's open `components` object for the vendored union.
    const grafted = key === "bp/items" && vendorCopied > 1;
    if (grafted) {
      const components = schema.properties?.["minecraft:item"]?.properties?.components;
      if (components) components.tsType = "ItemComponents";
    }

    let rootName = pascalCase(schema.title || key);
    while (usedNames.has(rootName)) rootName = `${rootName}_`;
    usedNames.add(rootName);

    // Relative $refs like `../../common/floatrange.schema.json` only resolve
    // correctly when the document being compiled sits at the same depth as the
    // original, so the (possibly grafted) schema goes to a sibling file rather
    // than being handed over as a bare object.
    const shimFile = path.join(path.dirname(schemaFile), `.generator.${path.basename(schemaFile)}`);

    // The root type is named after the schema title, so setting it here is how
    // the deduplicated `rootName` gets applied.
    schema.title = rootName;

    let body;
    try {
      fs.writeFileSync(shimFile, JSON.stringify(schema), "utf8");
      body = await compileFromFile(shimFile, {
        bannerComment: "",
        declareExternallyReferenced: true,
        unreachableDefinitions: false,
        additionalProperties: !strict,
        // Prettier costs ~0.5s on the entity schema — by far the largest — and
        // the whole compile only re-runs when the schema version or the settings
        // change, so the readability is worth it.
        format: true,
      });
    } catch (e) {
      log(`⚠️  failed to compile ${key}: ${e.message}`);
      continue;
    } finally {
      fs.rmSync(shimFile, { force: true });
    }

    if (!looksLikeValidTs(body)) {
      log(`⚠️  ${key} compiled to invalid TypeScript, skipping it rather than breaking typecheck`);
      continue;
    }

    const outFile = path.join(outDir, `${key}.d.ts`);
    const toRoot = path.relative(path.dirname(outFile), outDir).replace(/\\/g, "/") || ".";
    const prefix = toRoot.startsWith(".") ? toRoot : `./${toRoot}`;

    const preamble = grafted
      ? [
          ...ITEM_COMPONENTS_UNION.map(
            (name) =>
              `import type { ${name} } from '${prefix}/vendor/bp/items/components/${name.replace(/Components$/, "")}';`,
          ),
          `export type ItemComponents = ${ITEM_COMPONENTS_UNION.join(" | ")};`,
          "",
        ].join("\n")
      : "";

    fs.mkdirSync(path.dirname(outFile), { recursive: true });
    fs.writeFileSync(outFile, `${HEADER}\n${preamble}${body}`, "utf8");

    categories.push({
      key,
      rootName,
      alias: categoryAlias(key, usedAliases, typePrefix),
      module: `./${key}`,
      fileMatch: Array.isArray(entry.fileMatch) ? entry.fileMatch : [],
    });
  }

  return categories;
}

/** The `McCategories` map every overload is keyed on. */
function indexDtsText(categories, schemaVersion) {
  const lines = [
    HEADER,
    `// Schema package version: ${schemaVersion}`,
    "",
    "/**",
    " * Every Minecraft document type the generator knows about, keyed by the",
    " * category tag you pass to `defineTemplate` / `defineMany`.",
    " */",
    "export interface McCategories {",
  ];

  for (const c of categories) {
    lines.push(`  '${c.key}': import('${c.module}').${c.rootName};`);
  }

  lines.push("}", "", "export type McCategory = keyof McCategories;", "");

  for (const c of categories) {
    lines.push(`export type { ${c.rootName} } from '${c.module}';`);
  }

  return lines.join("\n") + "\n";
}

/** Ambient declarations for the two sandbox globals. No imports at the top
 *  level, so this file stays a global script rather than becoming a module. */
function globalsDtsText(categories = [], typePrefix = "") {
  const many = `${typePrefix}Many`;
  const aliases = categories
    .map((c) => `/** \`${c.key}\` document. */\ndeclare type ${c.alias} = McCategories['${c.key}'];`)
    .join("\n");

  return `${HEADER}
type McCategories = import('./index').McCategories;
type McCategory = import('./index').McCategory;

// ── Document types ───────────────────────────────────────────────────────────
// Global aliases, so a plain template needs no import and no helper call:
//
//   export default {
//     format_version: '1.21.0',
//     'minecraft:block': { description: { identifier: 'example:my_block' } },
//   } satisfies ${typePrefix}Block;
//
// \`satisfies\` is erased at build time, so nothing reaches the sandbox.

${aliases}

/**
 * Shape of the \`[nameFn, dataFn, items]\` tuple, for plain multi-file templates:
 *
 * \`\`\`ts
 * type Options = { id: string };
 * export default [
 *   (o) => \`\${o.id}.json\`,
 *   (o) => ({ format_version: '1.21.0', 'minecraft:block': { description: { identifier: o.id } } }),
 *   [{ id: 'example:my_block' }],
 * ] satisfies ${many}<Options, ${typePrefix}Block>;
 * \`\`\`
 *
 * The callbacks' parameters infer from \`Options\`, so they need no annotations.
 */
declare type ${many}<T, D> = readonly [
  (item: T, index: number) => string | Promise<string>,
  (item: T, index: number) => D | Promise<D>,
  readonly T[],
];

// ── Optional helpers ─────────────────────────────────────────────────────────
// Equivalent to the \`satisfies\` forms above. Use them if you would rather not
// name the item type — \`defineMany\` infers it from the items array.

/**
 * Declare a single generated JSON document. The category tag picks the schema
 * the object is checked against, and the output lands next to the template
 * with the same basename.
 *
 * \`\`\`ts
 * export default defineTemplate('bp/blocks', {
 *   format_version: '1.21.0',
 *   'minecraft:block': { description: { identifier: 'example:my_block' } },
 * });
 * \`\`\`
 */
declare function defineTemplate<K extends McCategory>(category: K, data: McCategories[K]): McCategories[K];
/** Untagged form — no schema checking, kept for templates that predate the tags. */
declare function defineTemplate<T extends object>(data: T): T;

/**
 * Declare a batch of generated JSON documents. \`items\` drives the type of the
 * argument both callbacks receive, so the parameters infer without annotation.
 *
 * \`\`\`ts
 * export default defineMany(
 *   'bp/blocks',
 *   (o) => \`\${o.id}.json\`,
 *   (o) => ({ format_version: '1.21.0', 'minecraft:block': { description: { identifier: o.id } } }),
 *   [{ id: 'example:my_block' }],
 * );
 * \`\`\`
 */
declare function defineMany<K extends McCategory, T>(
  category: K,
  name: (item: T, index: number) => string | Promise<string>,
  data: (item: T, index: number) => McCategories[K] | Promise<McCategories[K]>,
  items: readonly T[],
): unknown;
/** Untagged form — no schema checking. */
declare function defineMany<T, D extends object>(
  name: (item: T, index: number) => string | Promise<string>,
  data: (item: T, index: number) => D | Promise<D>,
  items: readonly T[],
): unknown;
`;
}

module.exports = { compileCatalog, indexDtsText, globalsDtsText, categoryKey, TYPES_REVISION };
