// Generates i18n.generated.d.ts — the committed declaration that types the
// '@bedrock-core/generated/i18n' bundle module for the IDE without a build.
//
// The root of the resource tree is `typeof import('./<defaultLocale>')` — the
// authored literal types pass through untouched, which is what makes key and
// interpolation-variable inference work. Library branches reference each
// package's exported resources (`<pkg>/i18n/<locale>`), vanilla references the
// sibling ambient module. The runtime JSON carries flat tables; `resources` is
// a type-only phantom the runtime never materializes.

/**
 * @param {{
 *   defaultLocale: string,
 *   vanilla: boolean,
 *   libs: Array<{ namespace: string, typeRefs: string[] }>,
 * }} opts
 * @returns {string}
 */
export function bundleDtsText({ defaultLocale, vanilla, libs }) {
  const libAliases = libs.map(({ namespace, typeRefs }) => {
    const refs = typeRefs.map((ref) => `typeof import('${ref}').default`).join(' & ');
    return `\ttype Lib_${namespace} = ${refs};`;
  });

  const branches = [
    ...libs.map(({ namespace }) => `readonly ${namespace}: Lib_${namespace};`),
    ...(vanilla ? [`readonly vanilla: import('@bedrock-core/generated/i18n-vanilla').VanillaResources;`] : []),
  ];

  // Authored overrides live under the branch names inside Own (e.g. a
  // `core.addons.title` rename) — Omit them so the graft replaces rather than
  // intersects, which would collapse overridden literals to `never`.
  const branchNames = [...libs.map(({ namespace }) => `'${namespace}'`), ...(vanilla ? ["'vanilla'"] : [])];
  const resourcesType = branches.length > 0
    ? `Omit<Own, ${branchNames.join(' | ')}> & {\n\t\t\t${branches.join('\n\t\t\t')}\n\t\t}`
    : 'Own';

  return [
    '// Auto-generated by the i18n Regolith filter. Do not edit — regenerated every build.',
    "declare module '@bedrock-core/generated/i18n' {",
    `\ttype Own = typeof import('./${defaultLocale}').default;`,
    ...libAliases,
    '',
    '\tconst bundle: {',
    '\t\treadonly namespace: string;',
    `\t\treadonly defaultLocale: '${defaultLocale}';`,
    `\t\treadonly libs: readonly [${libs.map(({ namespace }) => `'${namespace}'`).join(', ')}];`,
    '\t\t/** locale → flat path → template ({{var}} form; vanilla entries only where referenced) */',
    '\t\treadonly locales: Record<string, Record<string, string>>;',
    '\t\t/** flat path → interpolation argument order (default locale appearance order) */',
    '\t\treadonly args: Record<string, readonly string[]>;',
    '\t\t/** locale → REAL key → value: .lang passthrough (guides, hand-written) for measurement */',
    '\t\treadonly extra: Record<string, Record<string, string>>;',
    '\t\t/** Type-only: the tree the t()/key()/raw() selectors navigate. Absent at runtime. */',
    `\t\treadonly resources?: ${resourcesType};`,
    '\t};',
    '\texport default bundle;',
    '}',
    '',
  ].join('\n');
}
