// .lang file handling: parse, and idempotent upsert of the marker-delimited
// generated section (strip any previous section, then append the new one).
// Same scheme as the guides filter, distinct markers — each filter rewrites
// only its own section and hand-written entries are left untouched.

export const SECTION_BEGIN = '## <core:generated-i18n:begin> do not edit — generated by the i18n regolith filter';
export const SECTION_END = '## <core:generated-i18n:end>';

/** The branch holding the manifest display strings (name/description/creator). */
export const META_BRANCH = 'meta';

/**
 * Parse a Minecraft .lang file into a key→value map.
 * Lines starting with # are comments; blank lines are skipped.
 * Format: key=value (value may contain '=').
 */
export function parseLang(content: string): Record<string, string> {
  const map: Record<string, string> = {};
  for (const rawLine of content.split('\n')) {
    // Only the line ending goes: a value's trailing space is significant. A
    // guide paragraph is split into runs at its links, so "Back to " ends in
    // the space that separates it from the link; the client draws that space
    // and a build that measured the trimmed value boxed the label one space
    // too narrow, and the client ellipsised it.
    const line = rawLine.endsWith('\r') ? rawLine.slice(0, -1) : rawLine;
    if (!line.trim() || line.trimStart().startsWith('#')) continue;
    const eqIdx = line.indexOf('=');
    if (eqIdx === -1) continue;
    const key = line.slice(0, eqIdx).trim();
    const value = line.slice(eqIdx + 1);
    if (key) map[key] = value;
  }
  return map;
}

/** Remove a previously generated section (returns content unchanged if none). */
export function stripGeneratedSection(content: string): string {
  const begin = content.indexOf(SECTION_BEGIN);
  if (begin === -1) return content;
  const endMarker = content.indexOf(SECTION_END, begin);
  const end = endMarker === -1 ? content.length : endMarker + SECTION_END.length;
  return (content.slice(0, begin) + content.slice(end)).replace(/\n{3,}$/, '\n\n');
}

/**
 * The subset a behavior pack needs: the addon's OWN `meta` branch, already in
 * real-key form (`<namespace>.meta.*`).
 *
 * A pack's manifest `header.name` / `header.description` resolve from THAT
 * pack's own `texts/<locale>.lang`, so the BP needs the display strings in its
 * own file — but only those. Library keys never match: they carry their
 * library's namespace, not the addon's.
 *
 * Empty when the addon declares no `meta` branch.
 */
export function selectMetaEntries(entries: Map<string, string>, namespace: string): Map<string, string> {
  const branch = `${namespace}.${META_BRANCH}`;
  const out = new Map<string, string>();
  for (const [key, value] of entries) {
    if (key === branch || key.startsWith(`${branch}.`)) out.set(key, value);
  }
  return out;
}

/**
 * Replace/append the generated section. Keys are emitted sorted for
 * deterministic output. `.lang` values must be single-line — enforced here
 * as a last line of defense (flattenResources rejects newlines first).
 */
export function upsertGeneratedSection(content: string, entries: Map<string, string>): string {
  const base = stripGeneratedSection(content).replace(/\s+$/, '');

  const lines = [SECTION_BEGIN];
  for (const key of [...entries.keys()].sort()) {
    lines.push(`${key}=${String(entries.get(key)).replace(/\r?\n/g, ' ')}`);
  }
  lines.push(SECTION_END);

  return (base ? base + '\n\n' : '') + lines.join('\n') + '\n';
}

/**
 * The two literal keys Bedrock resolves a manifest header from. This is NOT a
 * general key lookup: the client reads `header.name` / `header.description`
 * only when they are exactly these strings, so `<namespace>.meta.name` in a
 * manifest shows up as the raw key in the pack list.
 */
export const MANIFEST_ALIASES: [leaf: string, alias: string][] = [
  ['name', 'pack.name'],
  ['description', 'pack.description'],
];

/**
 * Mirror the addon's `meta.name` / `meta.description` onto the literal
 * `pack.name` / `pack.description` keys, so a manifest can point at them.
 *
 * The namespaced originals stay — scripts resolve those through `key()`, and
 * they are what travels in the runtime bundle. These are aliases, emitted into
 * each pack's own generated section (both packs: RP and BP each have a
 * manifest of their own, and each resolves from its own texts file).
 *
 * Empty when neither display string is declared.
 */
export function manifestAliasEntries(entries: Map<string, string>, namespace: string): Map<string, string> {
  const out = new Map<string, string>();
  for (const [leaf, alias] of MANIFEST_ALIASES) {
    const value = entries.get(`${namespace}.${META_BRANCH}.${leaf}`);
    if (value !== undefined) out.set(alias, value);
  }
  return out;
}
