// Vanilla lang: fetch per locale from Mojang's bedrock-samples (cached under
// .regolith/cache/i18n/), and generate the vanilla key tree as an ambient
// module so `$.vanilla.*` autocompletes without the strings ever entering the
// RP — the client already ships them.

import fs from 'node:fs';
import path from 'node:path';

import { parseLang } from './lang.js';

export const VANILLA_LANG_URL_TEMPLATE =
  'https://raw.githubusercontent.com/Mojang/bedrock-samples/refs/heads/main/resource_pack/texts/{locale}.lang';

/**
 * @param {string} locale
 * @param {{ urlTemplate: string, cacheDir: string, maxAgeHours: number, log(msg: string): void }} opts
 * @returns {Promise<Record<string, string>>} key → vanilla display string
 */
export async function fetchVanillaLang(locale, { urlTemplate, cacheDir, maxAgeHours, log }) {
  const url = urlTemplate.replaceAll('{locale}', locale);
  const cacheFile = path.join(cacheDir, `vanilla-${locale}.lang.cache`);

  if (fs.existsSync(cacheFile)) {
    const ageHours = (Date.now() - fs.statSync(cacheFile).mtimeMs) / (1000 * 60 * 60);
    if (ageHours < maxAgeHours) {
      log(`✅ [${locale}] using cached vanilla lang (age: ${ageHours.toFixed(1)}h)`);
      return parseLang(fs.readFileSync(cacheFile, 'utf-8'));
    }
    log(`⏳ [${locale}] vanilla cache expired (${ageHours.toFixed(1)}h old), re-fetching…`);
  } else {
    log(`⏳ [${locale}] fetching vanilla lang from ${url} …`);
  }

  const res = await fetch(url);
  if (!res.ok) throw new Error(`[${locale}] HTTP ${res.status} ${res.statusText} — ${url}`);
  const text = await res.text();

  fs.mkdirSync(cacheDir, { recursive: true });
  fs.writeFileSync(cacheFile, text, 'utf-8');
  log(`✅ [${locale}] fetched and cached vanilla lang`);

  return parseLang(text);
}

/**
 * Build the `vanilla.generated.d.ts` content: the full vanilla key set as a
 * nested type inside an ambient module, so it resolves from anywhere without
 * path gymnastics. Leaves are `string`; a key that is both a full key AND a
 * prefix of longer keys ("item.apple" next to "item.apple.name") becomes
 * `{ …children } & string`, which keeps both selector navigation and
 * leaf-detection working.
 *
 * @param {Iterable<string>} keys
 * @returns {string}
 */
export function vanillaDtsText(keys) {
  /** @typedef {{ children: Map<string, Node>, leaf: boolean }} Node */
  const root = { children: new Map(), leaf: false };

  for (const key of keys) {
    let node = root;
    for (const segment of key.split('.')) {
      if (segment === '') { node = null; break; }
      let child = node.children.get(segment);
      if (!child) {
        child = { children: new Map(), leaf: false };
        node.children.set(segment, child);
      }
      node = child;
    }
    if (node) node.leaf = true;
  }

  const emit = (node, indent) => {
    const pad = '\t'.repeat(indent);
    const lines = ['{'];
    for (const name of [...node.children.keys()].sort()) {
      const child = node.children.get(name);
      const value = child.children.size === 0 ? 'string' : emit(child, indent + 1) + (child.leaf ? ' & string' : '');
      lines.push(`${pad}\treadonly '${name}': ${value};`);
    }
    lines.push(`${pad}}`);
    return lines.join('\n');
  };

  return [
    '// Auto-generated by the i18n Regolith filter. Do not edit — regenerated when the',
    '// cached vanilla lang changes. Types only: these strings are never emitted into',
    '// the RP (the client ships them), and only the keys your scripts reference are',
    '// bundled for server-side resolution.',
    "declare module '@bedrock-core/generated/i18n-vanilla' {",
    `\texport interface VanillaResources ${emit(root, 1)}`,
    '}',
    '',
  ].join('\n');
}
