// The typed handle: what the behaviour pack imports to drive a compiled screen.
//
// It is committed into the project, not just the build output, so it has to read
// like hand-written source — the repo lints and type-checks it alongside
// everything else.
//
// Everything here is POSITIONAL. Nothing in a screen is named any more: a
// handler is a prop on the component, and the runtime matches it to a slot by
// walking the re-rendered tree in the same order the compiler walked the
// laid-out one. That works because the shape is frozen — the nth slot of one
// render is the nth slot of the next — and it is why the author never sees an
// index or invents a name.

const ESCAPE = /['\\]/g;

const quoted = value => `'${String(value).replace(ESCAPE, match => `\\${match}`)}'`;

/**
 * @param {object} screen
 * @param {string} screen.name
 * @param {string} screen.namespace
 * @param {number} screen.layoutId
 * @param {{ sentinel: number, drawn: number, channels: number, size: number }} screen.allocation
 * @param {{ slot: number, role: string }[]} screen.slots
 * @param {{ slot: number, carrier: string, length: number }[]} screen.channels
 * @param {string | undefined} screen.entity
 * @param {string} screen.source module specifier of the screen component
 * @returns {string} TypeScript source
 */
export function buildHandle(screen) {
  const slotEntries = screen.slots
    .map(slot => `  { slot: ${slot.slot}, role: ${quoted(slot.role)} },`)
    .join('\n');

  const channelEntries = screen.channels
    .map(channel => `  { slot: ${channel.slot}, `
      + `carrier: ${quoted(channel.carrier)}, length: ${channel.length} },`)
    .join('\n');

  return `// GENERATED by the ui-compile filter — do not edit.
//
// Compiled from the screen of the same name. Every number below is an
// allocation the compiler made, and every list is in the order the screen
// declares them — which is the order the runtime re-renders them in.

import Screen from ${quoted(screen.source)};

/**
 * Where each drawn slot is, and what the player may do with it.
 *
 * In document order, matching the order slots appear in the component. The role
 * belongs to the SCREEN rather than to a script: a furnace's output slot is an
 * output slot whatever is attached to it. The runtime enforces it a tick after
 * the fact, because a container gives no way to veto a move.
 */
export const slots = [
${slotEntries}
] as const;

/**
 * Where each channel lives and how wide it is, in document order.
 *
 * A \`text\` channel spans one container slot per character: the code rides that
 * slot's stack size, which is the only value writable in place, and the layout
 * localizes it back into a glyph.
 */
export const channels = [
${channelEntries}
] as const;

export const screen = {
  /** JSON UI namespace the layout was emitted into. */
  namespace: ${quoted(screen.namespace)},
  /** Written into the sentinel's durability so the router can pick this layout. */
  layoutId: ${screen.layoutId},
  /** Carries the routing keys. Never drawn. */
  sentinelSlot: ${screen.allocation.sentinel},
  /** Slots the layout draws: \`1 .. drawn\`. */
  drawn: ${screen.allocation.drawn},
  /** Bank slots backing channels, immediately after the drawn range. */
  channelCount: ${screen.allocation.channels},
  /** What \`minecraft:inventory\` on the host entity must be sized to. */
  inventorySize: ${screen.allocation.size},
  /** Entity the screen was attached to, if the source named one. */
  entity: ${screen.entity === undefined ? 'undefined' : quoted(screen.entity)},
} as const;

/** The component itself, re-rendered per player to produce the live values. */
export { Screen };
`;
}
