// The typed handle: what the behaviour pack imports to drive a compiled screen.
//
// It is committed into the project, not just the build output, so it has to read
// like hand-written source — the repo lints and type-checks it alongside
// everything else.
//
// Slot indices, the bank layout and the layout key are all compiler decisions,
// so the script must never restate them — it addresses slots by the names the
// screen used, and everything numeric is generated here. Renaming a slot in the
// .tsx becomes a type error in the script rather than a silent no-op in game.

const ESCAPE = /['\\]/g;

const quoted = value => `'${String(value).replace(ESCAPE, match => `\\${match}`)}'`;

/** Bare where it is a valid identifier, quoted only where it has to be. */
const key = name => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : quoted(name));

/**
 * @param {object} screen
 * @param {string} screen.name
 * @param {string} screen.namespace
 * @param {number} screen.layoutId
 * @param {{ sentinel: number, drawn: number, channels: number, size: number }} screen.allocation
 * @param {{ name: string, slot: number, role: string }[]} screen.slots
 * @param {{ name: string, slot: number, carrier: string, length: number }[]} screen.channels
 * @param {string | undefined} screen.entity
 * @returns {string} TypeScript source
 */
export function buildHandle(screen) {
  const slotEntries = screen.slots
    .map(slot => `  ${key(slot.name)}: { slot: ${slot.slot}, role: ${quoted(slot.role)} },`)
    .join('\n');

  const channelEntries = screen.channels
    .map(channel => `  ${key(channel.name)}: `
      + `{ slot: ${channel.slot}, carrier: ${quoted(channel.carrier)}, length: ${channel.length} },`)
    .join('\n');

  const slotUnion = screen.slots.length > 0
    ? screen.slots.map(slot => quoted(slot.name)).join(' | ')
    : 'never';

  const channelUnion = screen.channels.length > 0
    ? screen.channels.map(channel => quoted(channel.name)).join(' | ')
    : 'never';

  return `// GENERATED by the ui-compile filter — do not edit.
//
// Compiled from the screen of the same name. Every number below is an
// allocation the compiler made; address slots by name and they stay correct
// when the layout moves.

/** Slot names this screen draws, in the order it draws them. */
export type SlotName = ${slotUnion};

/** Channel names this screen reads. */
export type ChannelName = ${channelUnion};

/**
 * Where each drawn slot is, and what the player may do with it.
 *
 * The role belongs to the SCREEN rather than to the script: a furnace's output
 * slot is an output slot whatever is attached to it. The runtime enforces it a
 * tick after the fact, because a container gives no way to veto a move.
 */
export const slots = {
${slotEntries}
} as const satisfies Record<SlotName, { slot: number; role: 'both' | 'input' | 'output' | 'button' }>;

/**
 * Where each channel lives and how wide it is.
 *
 * A \`text\` channel spans one slot per character: the code rides that slot's
 * stack size, which is the only value writable in place, and the layout
 * localizes it back into a glyph.
 */
export const channels = {
${channelEntries}
} as const satisfies Record<ChannelName, { slot: number; carrier: 'ratio' | 'text'; length: number }>;

export const screen = {
  /** JSON UI namespace the layout was emitted into. */
  namespace: ${quoted(screen.namespace)},
  /** Written into the sentinel's durability so the router can pick this layout. */
  layoutId: ${screen.layoutId},
  /** Carries the routing keys. Never drawn. */
  sentinelSlot: ${screen.allocation.sentinel},
  /** Slots the layout draws: \`1 .. drawn\`. */
  drawn: ${screen.allocation.drawn},
  /** Bank slots backing channels, immediately after the drawn range. */
  channelCount: ${screen.allocation.channels},
  /** What \`minecraft:inventory\` on the host entity must be sized to. */
  inventorySize: ${screen.allocation.size},
  /** Entity the screen was attached to, if the source named one. */
  entity: ${screen.entity === undefined ? 'undefined' : quoted(screen.entity)},
} as const;
`;
}
