// .lang file handling: parse, and idempotent upsert of the marker-delimited
// generated section (strip any previous section, then append the new one).

export const SECTION_BEGIN = '## <bcg:generated-guides:begin> do not edit — generated by the guides regolith filter';
export const SECTION_END = '## <bcg:generated-guides:end>';

/**
 * Parse a Minecraft .lang file into a key→value map.
 * Lines starting with # are comments; blank lines are skipped.
 * Format: key=value (value may contain '=').
 *
 * @param {string} content
 * @returns {Record<string, string>}
 */
export function parseLang(content) {
  const map = {};
  for (const rawLine of content.split('\n')) {
    const line = rawLine.trimEnd();
    if (!line || line.startsWith('#')) continue;
    const eqIdx = line.indexOf('=');
    if (eqIdx === -1) continue;
    const key = line.slice(0, eqIdx).trim();
    const value = line.slice(eqIdx + 1); // preserve leading spaces in value
    if (key) map[key] = value;
  }
  return map;
}

/** Remove a previously generated section (returns content unchanged if none). */
export function stripGeneratedSection(content) {
  const begin = content.indexOf(SECTION_BEGIN);
  if (begin === -1) return content;
  const endMarker = content.indexOf(SECTION_END, begin);
  const end = endMarker === -1 ? content.length : endMarker + SECTION_END.length;
  return (content.slice(0, begin) + content.slice(end)).replace(/\n{3,}$/, '\n\n');
}

/**
 * Replace/append the generated section. Keys are emitted sorted for
 * deterministic output. `.lang` values must be single-line — enforced here
 * as a last line of defense (the inline compiler never emits newlines).
 *
 * @param {string} content   existing file content ('' for a new file)
 * @param {Map<string, string>} entries
 * @returns {string}
 */
export function upsertGeneratedSection(content, entries) {
  const base = stripGeneratedSection(content).replace(/\s+$/, '');

  const lines = [SECTION_BEGIN];
  for (const key of [...entries.keys()].sort()) {
    lines.push(`${key}=${String(entries.get(key)).replace(/\r?\n/g, ' ')}`);
  }
  lines.push(SECTION_END);

  return (base ? base + '\n\n' : '') + lines.join('\n') + '\n';
}
