// Generated screen modules — one per guide page and one for the home index —
// dropped into the addon's scripts so the ui-compile filter compiles each as
// a form-action screen and the bundler ships it like any authored screen.
//
// A module is three lines: the manifest (imported RELATIVELY — a tsconfig
// alias would resolve against the project, and the manifest this build wrote
// lives in the Regolith workspace), the factory from @bedrock-core/guides,
// and the default export the compile expects. Pages become screens by NAME:
// `guide_<page id>` with every character outside [a-z0-9_] folded to `_`,
// which is what both the JSON UI namespace and the file basename accept.

import path from 'node:path';

export interface GuideScreenModule {
  /** Path relative to the Regolith workspace root. */
  file: string;
  source: string;
}

export interface GuideScreensInput {
  pageIds: Iterable<string>;
  /** Where the modules go, relative to the workspace root. */
  screensDir: string;
  /** Where the manifest was written, relative to the workspace root. */
  manifestPath: string;
  /** Header title baked into every screen. */
  title: string;
  /**
   * Module whose default export is the `cmp` component registry, relative to
   * the workspace root. Absent, a `cmp` block renders the placeholder.
   */
  components?: string;
}

/** The home index's screen name; no page may fold to it. */
export const HOME_SCREEN = 'guide_home';

/** `getting-started/intro` → `guide_getting_started_intro`. */
export const guideScreenName = (pageId: string): string =>
  `guide_${pageId.toLowerCase().replace(/[^a-z0-9_]/g, '_')}`;

const toPosix = (p: string): string => p.replaceAll('\\', '/');

const HEADER = '// GENERATED by the guides filter — do not edit.\n'
  + '// One guide page as a screen; the ui-compile filter bakes it into the pack.\n';

/** An import specifier for `target` as written from a module in `from`. */
const specifierFrom = (from: string, target: string): string => {
  const relative = toPosix(path.relative(from, target));

  return relative.startsWith('.') ? relative : `./${relative}`;
};

export function guideScreenModules({ pageIds, screensDir, manifestPath, title, components }: GuideScreensInput): GuideScreenModule[] {
  const specifier = specifierFrom(screensDir, manifestPath);
  const registry = components === undefined ? undefined : specifierFrom(screensDir, components.replace(/\.tsx?$/, ''));
  const registryImport = registry === undefined ? '' : `import components from ${JSON.stringify(registry)};\n`;
  const pageOptions = `{ title: ${JSON.stringify(title)}${registry === undefined ? '' : ', components'} }`;
  const owners = new Map<string, string>([[HOME_SCREEN, '(the home index)']]);
  const modules: GuideScreenModule[] = [{
    file: toPosix(path.join(screensDir, `${HOME_SCREEN}.screen.tsx`)),
    source: `${HEADER}import manifest from ${JSON.stringify(specifier)};\n`
      + 'import { guideHomeScreen } from \'@bedrock-core/guides\';\n\n'
      + `export default guideHomeScreen(manifest, { title: ${JSON.stringify(title)} });\n`,
  }];

  for (const pageId of [...pageIds].sort()) {
    const name = guideScreenName(pageId);
    const taken = owners.get(name);

    if (taken !== undefined) {
      throw new Error(`pages "${taken}" and "${pageId}" both compile to the screen "${name}"; rename one so they differ in [a-z0-9]`);
    }

    owners.set(name, pageId);
    modules.push({
      file: toPosix(path.join(screensDir, `${name}.screen.tsx`)),
      source: `${HEADER}import manifest from ${JSON.stringify(specifier)};\n`
        + registryImport
        + 'import { guidePageScreen } from \'@bedrock-core/guides\';\n\n'
        + `export default guidePageScreen(manifest, ${JSON.stringify(pageId)}, ${pageOptions});\n`,
    });
  }

  return modules;
}
